### ISSUE TITLE
쿠폰 발급 api 개발

### ISSUE THREAD

**Issue by cire0304** [f-lab-edu/AYU-Coupon-Service#8]
## ☑️ 진행할 작업

쿠폰 발급을 위한 API 개발

## 📝 TODO

- [ ] 쿠폰 UI 계층 개발
- [ ] 쿠폰 서비스 계층 개발
- [ ] 쿠폰 도메인 엔티티 개발
- [ ] 쿠폰 영속성 계층 개발

**Comment by cire0304** [comment]
이슈 크기를 줄이기 위해 close 합니다.
